version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.8.3-full
    # ports:
    #   - 5005:5005
    volumes:
      - ./:/app
    command:
      - train
  action-server:
    image: rasa/rasa-sdk:2.8.1
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
  webchat:
    image: rasa/rasa:2.8.3-full
    container_name: rasa-webchat
    ports:
      - 5005:5005
    volumes: 
      - ./:/app
    depends_on: 
      - rasa
    command: run -m models --enable-api --cors "*"
  